"""empty message

Revision ID: 657d15065308
Revises: 2ca2c768bb9c
Create Date: 2021-07-09 11:07:18.252902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657d15065308'
down_revision = '2ca2c768bb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_session_id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['todo_sessions.id'], ),
    sa.ForeignKeyConstraint(['todo_session_id'], ['todo_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('session_exercise', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercise', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('todo_exercises')
    # ### end Alembic commands ###
