"""empty message

Revision ID: 31d231a04036
Revises: 657d15065308
Create Date: 2021-07-09 11:09:08.723787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d231a04036'
down_revision = '657d15065308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_sessions', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('todo_sessions', sa.Column('date_completed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_sessions', 'date_completed')
    op.drop_column('todo_sessions', 'completed')
    # ### end Alembic commands ###
