"""empty message

Revision ID: e6a8356e7e01
Revises: 844066a387c4
Create Date: 2021-06-29 19:02:27.871515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a8356e7e01'
down_revision = '844066a387c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('skill_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercises', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'skill_id')
    # ### end Alembic commands ###
