"""empty message

Revision ID: 2ca2c768bb9c
Revises: 2dec7f1e32bc
Create Date: 2021-07-07 11:39:35.696613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca2c768bb9c'
down_revision = '2dec7f1e32bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todo_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_sessions', type_='foreignkey')
    op.drop_column('todo_sessions', 'user_id')
    # ### end Alembic commands ###
