"""empty message

Revision ID: dd141aa86665
Revises: e6a8356e7e01
Create Date: 2021-07-01 16:45:53.556613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd141aa86665'
down_revision = 'e6a8356e7e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('exercises', 'notes')
    # ### end Alembic commands ###
